In [ ]:
import numpy as np

**upload the data**

In [ ]:
data_file = "/makeSenseOfCensus.csv"

In [ ]:
data = np.genfromtxt(data_file, delimiter=",",skip_header =1)

**print the data**

In [ ]:
# printing the data
print('\nData: \n\n', data)


Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


In [ ]:
# printing the type of data
print("\ntype of data: \n\n", type(data))


type of data: 

 <class 'numpy.ndarray'>


In [ ]:
data.shape

(1000, 8)

In [ ]:
data.size

8000

In [ ]:
data.ndim

2

**Append the new data**

In [ ]:
hima = [[21,15,4,0,0,0,35,0]]

In [ ]:
hima

[[21, 15, 4, 0, 0, 0, 35, 0]]

In [ ]:
data = np.concatenate((data,hima))

In [ ]:
data

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [21., 15.,  4., ...,  0., 35.,  0.]])

In [ ]:
data.shape

(1001, 8)

In [ ]:
data.size

8008

**question : check if it is young country or old country**

create a new array called 'age' by taking only age column (age column with index 0) of census array

In [ ]:

age = data[:,0]

find the maximum age and store it in a variable called 'max_age'
age.max

In [ ]:
max_age = np.max(age)

In [ ]:
print(max_age)

90.0


Find the min age and store it in a variable called 'min_age'

In [ ]:
min_age = np.min(age)

In [ ]:
min_age

17.0

he mean of the age and store it in a variable called 'age_mean'.

In [ ]:
# mean means average
age_mean = np.mean(age)

In [ ]:
age_mean

38.03396603396603

Find the standard deviation of the age and store it in a variable called 'age_std'

In [ ]:
age_std = np.std(age)

In [ ]:
age_std

13.347010993192175

**Let's check the country's race distribution to identify the minorities**


Create four different arrays by subsetting 'census' array by Race column(Race is the column with index 2) and save them in 'race_0','race_1', 'race_2', 'race_3' and 'race_4' respectively(Meaning: Store the array where 'race'column has value 0 in 'race_0', so on and so forth)

In [ ]:
race = data[:,2]

In [ ]:
race

array([4., 4., 4., ..., 4., 4., 4.])

In [ ]:
np.unique(race)

array([0., 1., 2., 3., 4.])

In [ ]:
race_0 = race[race == 0]
race_1 = race[race==1]
race_2 = race[race == 2]
race_3 = race[race == 3]
race_4 = race[race ==4]

Store the length of the above created arrays in 'len_0', 'len_1','len_2', 'len_3' and 'len_4' respectively

In [ ]:
len_0 = len(race_0)
len_0

10

In [ ]:
len_1 = len(race_1)
len_1

27

In [ ]:
len_2 = len(race_2)
len_2

110

In [ ]:
len_3 = len(race_3)
len_3

6

In [ ]:
len_4 = len(race_4)
len_4

848

Find out which is the race with the minimum no. of citizens



In [ ]:
race_len = [len_0,len_1,len_2,len_3,len_4]


In [ ]:
race_len

[10, 27, 110, 6, 848]

Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

In [ ]:
minority_race = np.argmin(race_len)

In [ ]:
minority_race

3

In [ ]:
majority_race = np.argmax(race_len)

In [ ]:
majority_race

4

**As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place**

Create a new subset array called 'senior_citizens' by filtering 'census' according to age>60 (age is the column with index 0)

In [ ]:
senior_citizen = data[data[:,0]>60]

In [ ]:
senior_citizen

array([[7.9000e+01, 1.0000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+01, 0.0000e+00],
       [6.7000e+01, 6.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+00, 0.0000e+00],
       [7.6000e+01, 1.4000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 1.0000e+00],
       [6.1000e+01, 9.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 0.0000e+00],
       [7.0000e+01, 1.0000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 0.0000e+00],
       [6.4000e+01, 7.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        2.1790e+03, 4.0000e+01, 0.0000e+00],
       [7.1000e+01, 1.0000e+01, 2.0000e+00, 1.0000e+00, 0.0000e+00,
        1.8160e+03, 2.0000e+00, 0.0000e+00],
       [6.8000e+01, 2.0000e+00, 4.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+01, 0.0000e+00],
       [6.6000e+01, 1.1000e+01, 4.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+

Add all the working hours(working hours is the column with index 6) of 'senior_citizens' and store it in a variable called 'working_hours_sum'



In [ ]:
working_hours_sum = np.sum(senior_citizen[:,6])

In [ ]:
working_hours_sum

1917.0

Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len'

In [ ]:
senior_citizens_len = len(senior_citizen)

In [ ]:
senior_citizens_len

61

Finally find the average working hours of the senior citizens by dividing 'working_hours_sum' by 'senior_citizens_len' and store it in a variable called 'avg_working hours'.

In [ ]:
avg_working_hours = working_hours_sum/senior_citizens_len

In [ ]:
avg_working_hours

31.42622950819672

Print 'avg_working_hours' and see if the govt. policy is followed.

In [ ]:
print(avg_working_hours)

31.42622950819672


 **Let's check that higher educated people have better pay in general.**

Create two new subset arrays called 'high' and 'low' by filtering 'census' according to education-num>10 and education-num<=10 (education-num is the column with index 1) respectively.

In [ ]:
high = data[data[:,1]>10]

In [ ]:
high

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [28., 13.,  2., ...,  0., 40.,  0.],
       ...,
       [48., 13.,  4., ...,  0., 58.,  1.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [21., 15.,  4., ...,  0., 35.,  0.]])

In [ ]:
len(high)

328

In [ ]:
low = data[data[:,1]<10]

In [ ]:
low

array([[38.,  9.,  4., ...,  0., 40.,  0.],
       [53.,  7.,  2., ...,  0., 40.,  0.],
       [49.,  5.,  2., ...,  0., 16.,  0.],
       ...,
       [47.,  9.,  4., ...,  0., 50.,  1.],
       [35.,  9.,  4., ...,  0., 45.,  0.],
       [56.,  9.,  4., ...,  0., 55.,  1.]])

In [ ]:
len(low)

448

Find the mean of income column(income is the column with index 7) of 'high' array and store it in 'avg_pay_high'. Do the same for 'low' array and store it's mean in 'avg_pay_low'.

In [ ]:
avg_pay_high =np.mean(high[:,7])

In [ ]:
avg_pay_high

0.4268292682926829

In [ ]:
avg_pay_low = np.mean(low[:,7])

In [ ]:
avg_pay_low

0.12723214285714285