Instructions:
Load the data. Data is already given to you in variable path

How many unique ad campaigns (xyzcampaignid) does this data contain ? And for how many times was each campaign run ?

What are the age groups that were targeted through these ad campaigns?

What was the average, minimum and maximum amount spent on the ads?

What is the id of the ad having the maximum number of clicks ?

How many people bought the product after seeing the ad with most clicks? Is that the maximum number of purchases in this dataset?

So the ad with the most clicks didn't fetch the maximum number of purchases. Find the details of the product having maximum number of purchases

In [ ]:
import numpy as np

In [ ]:
data_file = '/content/KAG_Conversion_Data.csv'

In [ ]:
data = np.genfromtxt(data_file,delimiter=",",skip_header=1)

In [ ]:
data

array([[7.08746000e+05, 9.16000000e+02, 1.03916000e+05, ...,
        1.42999995e+00, 2.00000000e+00, 1.00000000e+00],
       [7.08749000e+05, 9.16000000e+02, 1.03917000e+05, ...,
        1.82000002e+00, 2.00000000e+00, 0.00000000e+00],
       [7.08771000e+05, 9.16000000e+02, 1.03920000e+05, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       ...,
       [1.31441200e+06, 1.17800000e+03, 1.79979000e+05, ...,
        4.02899995e+01, 2.00000000e+00, 0.00000000e+00],
       [1.31441400e+06, 1.17800000e+03, 1.79981000e+05, ...,
        1.98710001e+02, 8.00000000e+00, 2.00000000e+00],
       [1.31441500e+06, 1.17800000e+03, 1.79982000e+05, ...,
        1.65609999e+02, 5.00000000e+00, 2.00000000e+00]])

In [ ]:
# extract the relevant columns
ad_id = data[:,0].astype(int)
xyz_campaign_id = data[:,1].astype(int)
fb_campaign_id = data[:,2].astype(int)
age = data[:,3]
spent = data[:,8].astype(float)
clicks = data[:,7].astype(int)
approved_conversion =data[:,10].astype(int)

In [ ]:
xyz_unique_campaign = np.unique(xyz_campaign_id).size

In [ ]:
xyz_unique_campaign

3

In [ ]:
fb_unique_campaign = np.unique(fb_campaign_id).size

In [ ]:
fb_unique_campaign

691

In [ ]:
campaign_ids,campaign_counts = np.unique(xyz_campaign_id,return_counts=True)

In [ ]:
campaign_runs = dict(zip(campaign_ids,campaign_counts))

In [ ]:
campaign_runs

{916: 54, 936: 464, 1178: 625}

In [ ]:
targeted_age_groups = np.unique(age)

In [ ]:
targeted_age_groups

array([nan])

In [ ]:
average_spent = np.mean(spent)

In [ ]:
average_spent

51.36065613141295

In [ ]:
minimum_spent = np.min(spent)

In [ ]:
minimum_spent

0.0

In [ ]:
maximum_spent =np.max(spent)

In [ ]:
maximum_spent

639.9499981

In [ ]:
max_clicks_index = np.argmax(clicks)

In [ ]:
max_clicks_ad_id = ad_id[max_clicks_index]

In [ ]:
max_clicks =clicks[max_clicks_index]

In [ ]:
max_clicks

421

In [ ]:
purchases_max_clicks = approved_conversion[max_clicks_index]

In [ ]:
purchases_max_clicks

13

In [ ]:
max_purchases = np.max(approved_conversion)

In [ ]:
max_purchases

21

In [ ]:
max_purchases_index = np.argmax(approved_conversion)

In [ ]:
max_purchases_index

528

In [ ]:
max_purchases_ad_details= data[max_purchases_index]

In [ ]:
max_purchases_ad_details

array([1.12110400e+06, 1.17800000e+03, 1.44533000e+05,            nan,
                  nan, 1.60000000e+01, 2.08066600e+06, 2.02000000e+02,
       3.60150001e+02, 4.00000000e+01, 2.10000000e+01])